"""add extended school fields and is_application

Revision ID: b5877ff66cac
Revises: 
Create Date: 2025-05-24 22:54:53.091240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5877ff66cac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('school', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('successor_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('successor_inn', sa.String(length=12), nullable=True))
        batch_op.add_column(sa.Column('successor_address', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('is_application', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('school', schema=None) as batch_op:
        batch_op.drop_column('is_application')
        batch_op.drop_column('successor_address')
        batch_op.drop_column('successor_inn')
        batch_op.drop_column('successor_name')
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
